image: node:latest

stages:
    - prepare
    - test
    - build
    - deploy

cache:
    paths:
        - "node_modules"

prepare_env:
    stage: prepare
    script: yarn install

jest:
    stage: test
    script: yarn test
    only:
    - dev
    - /^issue-.*$/
    - merge_requests

main_build:
    stage: build
    script: yarn build
    only:
    - main
    - /^issue-.*$/
    - merge_requests

docs_build:
    stage: build
    script: yarn build:docs
    only:
    - main
    - /^issue-.*$/
    - merge_requests
